"""change type password

Revision ID: 43aabe5a4c45
Revises: 
Create Date: 2023-10-19 21:53:44.755442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from db.passwords import models

revision: str = '43aabe5a4c45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passwords',
                    sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('service_name', sa.String(), nullable=False),
                    sa.Column('password', models.HexByteString(), nullable=False),
                    sa.PrimaryKeyConstraint('pk'),
                    sa.UniqueConstraint('service_name')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passwords')
    # ### end Alembic commands ###
