"""add ForeignKey in passwords table (user_id)

Revision ID: ecea836e71a0
Revises: f206bec71640
Create Date: 2023-11-08 20:35:55.668132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecea836e71a0'
down_revision: Union[str, None] = 'f206bec71640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passwords', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'passwords', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'passwords', type_='foreignkey')
    op.drop_column('passwords', 'user_id')
    # ### end Alembic commands ###
