"""add table users

Revision ID: f206bec71640
Revises:
Create Date: 2023-11-08 20:18:06.545879

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from db import passwords


# revision identifiers, used by Alembic.
revision: str = "f206bec71640"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "passwords",
        sa.Column("pk", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("service_name", sa.String(), nullable=False),
        sa.Column("password", passwords.models.HexByteString(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("service_name"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("login", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_users_login"), "users", ["login"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_login"), table_name="users")
    op.drop_table("users")
    op.drop_table("passwords")
    # ### end Alembic commands ###
